
###register usera

POST http://localhost:4000/api/user/register HTTP/1.1
content-type: application/json

{    
   "name": "name3",
   "lastName": "lastName",
   "email":"na@emsail.pl",
   "password":"password"
}


### user potwierdza rejestrację konta z użyciem tokena

GET http://localhost:4000/api/user/confirm/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hQGVtc2FpbC5wbCIsImlhdCI6MTY4NTAzNzAyMiwiZXhwIjoxNjg1MDQwNjIyfQ.76Wn2jYm1j7kJszmRTUEW7OnFYIiZ8NlzStXFnUaXdA

###
POST http://localhost:4000/api/user/login HTTP/1.1
content-type: application/json

{
  "email":"name@email.pl",
  "password":"password"
}

# ### json all users - funkcja pomocnicza dla testów

# GET http://localhost:4000/api/user HTTP/1.1