
###register usera

POST http://localhost:4000/api/user/register HTTP/1.1
content-type: application/json

{    
   "name": "name3",
   "lastName": "lastName",
   "email":"name4@email.pl",
   "password":"password"
}


### user potwierdza rejestrację konta z użyciem tokena

GET http://localhost:4000/api/user/confirm/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbWU0QGVtYWlsLnBsIiwiaWF0IjoxNjg0ODI5NTE1LCJleHAiOjE2ODQ4MzMxMTV9.FQXsBcSV2sEzGBS47p9wCvE3vLa-dnCvu7h1qLrE1MQ HTTP/1.1


### logowanie z odesłaniem tokena po zalogowaniu - od tej pory każde żądanie zawiera token

POST http://localhost:4000/api/user/login HTTP/1.1
content-type: application/json

{
  "email":"name4@email.pl",
  "password":"password"
}

# ### json all users - funkcja pomocnicza dla testów

# GET http://localhost:4000/api/user HTTP/1.1